import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type LanguageCode = 'en' | 'fr' | 'es' | 'it' | 'pl' | 'ru' | 'de' | 'nl' | 'tr' | 'pt';

export const languageOptions = [
  { code: 'en', short: 'EN', flag: '🇬🇧', label: 'English' },
  { code: 'fr', short: 'FR', flag: '🇫🇷', label: 'Français' },
  { code: 'es', short: 'ES', flag: '🇪🇸', label: 'Español' },
  { code: 'it', short: 'IT', flag: '🇮🇹', label: 'Italiano' },
  { code: 'pl', short: 'PL', flag: '🇵🇱', label: 'Polski' },
  { code: 'ru', short: 'RU', flag: '🇷🇺', label: 'Русский' },
  { code: 'de', short: 'DE', flag: '🇩🇪', label: 'Deutsch' },
  { code: 'nl', short: 'NL', flag: '🇳🇱', label: 'Nederlands' },
  { code: 'tr', short: 'TR', flag: '🇹🇷', label: 'Türkçe' },
  { code: 'pt', short: 'PT', flag: '🇵🇹', label: 'Português' },
] as const;

const STORAGE_KEY = 'shopping-optimized-language';

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    guest: 'Guest',
    welcomeBack: '👋 Welcome back, {name}!',
    menu: 'Menu',
    list: 'List',
    service: 'Service',
    event: 'Event',
    withdrawal: 'Withdrawal',
    deposit: 'Deposit',
    terms: 'T & C',
    certificate: 'Certificate',
    faqs: 'FAQs',
    vipLevels: 'VIP Levels',
    viewMore: 'View More',
    vipReceive: 'Receive a set of {tasks} product optimization data tasks.',
    vipEach: 'Profit for each product optimization is {commission}.',
    vipCombined: 'Combined product optimization profit is {comboProfit}.',
    vipActivate: 'Activate with {amount}.',
    vipDaily: 'Up to 3 sets of product optimization data tasks can be completed per day.',
    home: 'Home',
    starting: 'Starting',
    records: 'Records',
    loginTagline: 'A responsive optimization workspace for web and mobile.',
    signInContinue: 'Sign in to continue optimizing tasks and tracking records.',
    loginPrompt: 'Login to continue optimizing tasks',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    login: 'Login',
    signingIn: 'Signing in...',
    faqP1: 'At the core of our philosophy is a strong commitment to you, our esteemed users. We understand that navigating a dynamic platform like ours can create questions and situations that standard FAQs cannot address. That is why our customer service team is always on standby, eager to provide you with personalised help and trusted insights.',
    faqP2: 'We do not just answer your questions, we provide solutions to ensure that your experience with us is seamless, enjoyable, and fulfilling. If you experience any challenge, please contact one of our customer service specialists, available from 10am to 10pm.',
    faqP3: 'Your satisfaction is not only our top priority, it is our passion. Allow us to guide you, support you, and celebrate every step of this remarkable journey with you.',
  },
  fr: {
    guest: 'Invité',
    welcomeBack: '👋 Bon retour, {name} !',
    menu: 'Menu',
    list: 'Liste',
    service: 'Service',
    event: 'Événement',
    withdrawal: 'Retrait',
    deposit: 'Dépôt',
    terms: 'C.G.U',
    certificate: 'Certificat',
    faqs: 'FAQs',
    vipLevels: 'Niveaux VIP',
    viewMore: 'Voir plus',
    vipReceive: 'Recevez un ensemble de {tasks} tâches d’optimisation de produits.',
    vipEach: 'Le profit pour chaque optimisation de produit est de {commission}.',
    vipCombined: 'Le profit combiné de l’optimisation est de {comboProfit}.',
    vipActivate: 'Activez avec {amount}.',
    vipDaily: 'Jusqu’à 3 ensembles de tâches peuvent être complétés par jour.',
    home: 'Accueil',
    starting: 'Démarrer',
    records: 'Historique',
    loginTagline: 'Un espace d’optimisation réactif pour le web et le mobile.',
    signInContinue: 'Connectez-vous pour continuer à optimiser et suivre vos tâches.',
    loginPrompt: 'Connectez-vous pour continuer',
    username: 'Nom d’utilisateur',
    password: 'Mot de passe',
    enterUsername: 'Entrez le nom d’utilisateur',
    enterPassword: 'Entrez le mot de passe',
    login: 'Connexion',
    signingIn: 'Connexion...',
    faqP1: 'Au cœur de notre philosophie se trouve un engagement fort envers vous, nos utilisateurs estimés. Nous savons qu’une plateforme dynamique comme la nôtre peut susciter des questions que les FAQ classiques ne couvrent pas. C’est pourquoi notre équipe d’assistance est toujours disponible pour vous accompagner.',
    faqP2: 'Nous ne répondons pas seulement à vos questions, nous vous apportons aussi des solutions pour rendre votre expérience simple, agréable et satisfaisante. En cas de difficulté, contactez l’un de nos spécialistes du service client, disponibles de 10h à 22h.',
    faqP3: 'Votre satisfaction n’est pas seulement notre priorité, c’est notre passion. Laissez-nous vous guider, vous soutenir et célébrer chaque étape de votre parcours.',
  },
  es: {
    guest: 'Invitado',
    welcomeBack: '👋 ¡Bienvenido de nuevo, {name}!',
    menu: 'Menú',
    list: 'Lista',
    service: 'Servicio',
    event: 'Evento',
    withdrawal: 'Retiro',
    deposit: 'Depósito',
    terms: 'Términos',
    certificate: 'Certificado',
    faqs: 'Preguntas frecuentes',
    vipLevels: 'Niveles VIP',
    viewMore: 'Ver más',
    vipReceive: 'Reciba un conjunto de {tasks} tareas de optimización de productos.',
    vipEach: 'La ganancia por cada optimización de producto es {commission}.',
    vipCombined: 'La ganancia combinada de optimización es {comboProfit}.',
    vipActivate: 'Activar con {amount}.',
    vipDaily: 'Se pueden completar hasta 3 conjuntos de tareas por día.',
    home: 'Inicio',
    starting: 'Empezar',
    records: 'Registros',
    loginTagline: 'Un espacio de optimización adaptable para web y móvil.',
    signInContinue: 'Inicia sesión para seguir optimizando y revisando registros.',
    loginPrompt: 'Inicia sesión para continuar',
    username: 'Usuario',
    password: 'Contraseña',
    enterUsername: 'Ingrese el usuario',
    enterPassword: 'Ingrese la contraseña',
    login: 'Entrar',
    signingIn: 'Entrando...',
    faqP1: 'En el centro de nuestra filosofía existe un fuerte compromiso con usted, nuestro estimado usuario. Sabemos que una plataforma dinámica como la nuestra puede generar preguntas que las FAQ estándar no siempre resuelven. Por eso, nuestro equipo de atención al cliente siempre está disponible para ayudarle.',
    faqP2: 'No solo respondemos preguntas, también ofrecemos soluciones para que su experiencia sea fluida, agradable y satisfactoria. Si tiene alguna dificultad, contacte con uno de nuestros especialistas, disponibles de 10:00 a 22:00.',
    faqP3: 'Su satisfacción no es solo nuestra prioridad, es nuestra pasión. Permítanos guiarle, apoyarle y celebrar cada paso de este recorrido con usted.',
  },
  it: {
    guest: 'Ospite',
    welcomeBack: '👋 Bentornato, {name}!',
    menu: 'Menu',
    list: 'Elenco',
    service: 'Servizio',
    event: 'Evento',
    withdrawal: 'Prelievo',
    deposit: 'Deposito',
    terms: 'Termini',
    certificate: 'Certificato',
    faqs: 'FAQ',
    vipLevels: 'Livelli VIP',
    viewMore: 'Vedi altro',
    vipReceive: 'Ricevi un set di {tasks} attività di ottimizzazione prodotti.',
    vipEach: 'Il profitto per ogni ottimizzazione prodotto è {commission}.',
    vipCombined: 'Il profitto combinato è {comboProfit}.',
    vipActivate: 'Attiva con {amount}.',
    vipDaily: 'Fino a 3 set di attività possono essere completati ogni giorno.',
    home: 'Home',
    starting: 'Avvio',
    records: 'Record',
    loginTagline: 'Uno spazio di ottimizzazione reattivo per web e mobile.',
    signInContinue: 'Accedi per continuare a ottimizzare e monitorare i record.',
    loginPrompt: 'Accedi per continuare',
    username: 'Nome utente',
    password: 'Password',
    enterUsername: 'Inserisci il nome utente',
    enterPassword: 'Inserisci la password',
    login: 'Accedi',
    signingIn: 'Accesso in corso...',
    faqP1: 'Al centro della nostra filosofia c’è un forte impegno verso di voi, i nostri stimati utenti. Sappiamo che una piattaforma dinamica come la nostra può generare domande che le FAQ standard non sempre coprono. Per questo il nostro team di assistenza è sempre pronto ad aiutarti.',
    faqP2: 'Non ci limitiamo a rispondere alle tue domande, ma forniamo soluzioni per rendere la tua esperienza semplice, piacevole e soddisfacente. Se incontri un problema, contatta uno dei nostri specialisti disponibili dalle 10 alle 22.',
    faqP3: 'La tua soddisfazione non è solo la nostra priorità, è la nostra passione. Lascia che ti guidiamo, ti supportiamo e celebriamo ogni passo del tuo percorso.',
  },
  pl: {
    guest: 'Gość',
    welcomeBack: '👋 Witaj ponownie, {name}!',
    menu: 'Menu',
    list: 'Lista',
    service: 'Serwis',
    event: 'Wydarzenie',
    withdrawal: 'Wypłata',
    deposit: 'Wpłata',
    terms: 'Regulamin',
    certificate: 'Certyfikat',
    faqs: 'FAQ',
    vipLevels: 'Poziomy VIP',
    viewMore: 'Zobacz więcej',
    vipReceive: 'Otrzymaj zestaw {tasks} zadań optymalizacji produktów.',
    vipEach: 'Zysk z każdej optymalizacji produktu wynosi {commission}.',
    vipCombined: 'Łączny zysk z optymalizacji wynosi {comboProfit}.',
    vipActivate: 'Aktywuj za {amount}.',
    vipDaily: 'Można ukończyć do 3 zestawów zadań dziennie.',
    home: 'Główna',
    starting: 'Start',
    records: 'Rekordy',
    loginTagline: 'Responsywna przestrzeń optymalizacji dla web i mobile.',
    signInContinue: 'Zaloguj się, aby kontynuować optymalizację i śledzenie wyników.',
    loginPrompt: 'Zaloguj się, aby kontynuować',
    username: 'Nazwa użytkownika',
    password: 'Hasło',
    enterUsername: 'Wpisz nazwę użytkownika',
    enterPassword: 'Wpisz hasło',
    login: 'Zaloguj się',
    signingIn: 'Logowanie...',
    faqP1: 'W centrum naszej filozofii znajduje się silne zaangażowanie wobec naszych użytkowników. Rozumiemy, że dynamiczna platforma taka jak nasza może rodzić pytania, których standardowe FAQ nie obejmują. Dlatego nasz zespół obsługi klienta jest zawsze gotowy do pomocy.',
    faqP2: 'Nie tylko odpowiadamy na pytania, ale także dostarczamy rozwiązania, aby Twoje doświadczenie było płynne i satysfakcjonujące. Jeśli napotkasz problem, skontaktuj się z jednym z naszych specjalistów dostępnych od 10:00 do 22:00.',
    faqP3: 'Twoja satysfakcja jest nie tylko naszym priorytetem, ale także naszą pasją. Pozwól nam Cię prowadzić i wspierać na każdym etapie tej podróży.',
  },
  ru: {
    guest: 'Гость',
    welcomeBack: '👋 С возвращением, {name}!',
    menu: 'Меню',
    list: 'Список',
    service: 'Сервис',
    event: 'Событие',
    withdrawal: 'Вывод',
    deposit: 'Депозит',
    terms: 'Условия',
    certificate: 'Сертификат',
    faqs: 'FAQ',
    vipLevels: 'VIP уровни',
    viewMore: 'Подробнее',
    vipReceive: 'Получите набор из {tasks} задач по оптимизации товаров.',
    vipEach: 'Прибыль за каждую оптимизацию товара составляет {commission}.',
    vipCombined: 'Совокупная прибыль составляет {comboProfit}.',
    vipActivate: 'Активировать за {amount}.',
    vipDaily: 'До 3 наборов задач можно выполнять ежедневно.',
    home: 'Главная',
    starting: 'Старт',
    records: 'Записи',
    loginTagline: 'Адаптивная платформа оптимизации для веба и мобильных устройств.',
    signInContinue: 'Войдите, чтобы продолжить оптимизацию и отслеживание записей.',
    loginPrompt: 'Войдите, чтобы продолжить',
    username: 'Имя пользователя',
    password: 'Пароль',
    enterUsername: 'Введите имя пользователя',
    enterPassword: 'Введите пароль',
    login: 'Войти',
    signingIn: 'Вход...',
    faqP1: 'В основе нашей философии лежит сильная приверженность вам, нашим уважаемым пользователям. Мы понимаем, что динамичная платформа, подобная нашей, может вызывать вопросы, на которые не всегда отвечают стандартные FAQ. Поэтому наша служба поддержки всегда готова помочь.',
    faqP2: 'Мы не просто отвечаем на вопросы, мы предлагаем решения, чтобы ваш опыт был удобным и приятным. Если у вас возникли трудности, свяжитесь с нашими специалистами службы поддержки, доступными с 10:00 до 22:00.',
    faqP3: 'Ваше удовлетворение — не только наш приоритет, но и наша страсть. Позвольте нам сопровождать и поддерживать вас на каждом этапе этого пути.',
  },
  de: {
    guest: 'Gast',
    welcomeBack: '👋 Willkommen zurück, {name}!',
    menu: 'Menü',
    list: 'Liste',
    service: 'Service',
    event: 'Ereignis',
    withdrawal: 'Auszahlung',
    deposit: 'Einzahlung',
    terms: 'AGB',
    certificate: 'Zertifikat',
    faqs: 'FAQ',
    vipLevels: 'VIP-Stufen',
    viewMore: 'Mehr sehen',
    vipReceive: 'Erhalten Sie ein Set mit {tasks} Produktoptimierungsaufgaben.',
    vipEach: 'Der Gewinn pro Produktoptimierung beträgt {commission}.',
    vipCombined: 'Der kombinierte Optimierungsgewinn beträgt {comboProfit}.',
    vipActivate: 'Aktivieren mit {amount}.',
    vipDaily: 'Bis zu 3 Aufgabensets können pro Tag abgeschlossen werden.',
    home: 'Start',
    starting: 'Starten',
    records: 'Verlauf',
    loginTagline: 'Ein responsiver Optimierungsbereich für Web und Mobilgeräte.',
    signInContinue: 'Melden Sie sich an, um Aufgaben weiter zu optimieren und zu verfolgen.',
    loginPrompt: 'Anmelden, um fortzufahren',
    username: 'Benutzername',
    password: 'Passwort',
    enterUsername: 'Benutzernamen eingeben',
    enterPassword: 'Passwort eingeben',
    login: 'Anmelden',
    signingIn: 'Anmeldung läuft...',
    faqP1: 'Im Mittelpunkt unserer Philosophie steht ein starkes Engagement für Sie, unsere geschätzten Nutzer. Wir wissen, dass eine dynamische Plattform wie unsere Fragen aufwerfen kann, die Standard-FAQ nicht immer beantworten. Deshalb steht unser Kundendienstteam jederzeit bereit.',
    faqP2: 'Wir beantworten nicht nur Fragen, sondern bieten auch Lösungen, damit Ihre Erfahrung reibungslos und angenehm bleibt. Wenn Sie ein Problem haben, wenden Sie sich bitte an einen unserer Kundendienstspezialisten, die von 10 bis 22 Uhr erreichbar sind.',
    faqP3: 'Ihre Zufriedenheit ist nicht nur unsere Priorität, sondern unsere Leidenschaft. Lassen Sie uns Sie begleiten, unterstützen und jeden Schritt Ihrer Reise mit Ihnen feiern.',
  },
  nl: {
    guest: 'Gast',
    welcomeBack: '👋 Welkom terug, {name}!',
    menu: 'Menu',
    list: 'Lijst',
    service: 'Service',
    event: 'Evenement',
    withdrawal: 'Opname',
    deposit: 'Storting',
    terms: 'Voorwaarden',
    certificate: 'Certificaat',
    faqs: 'FAQ',
    vipLevels: 'VIP-niveaus',
    viewMore: 'Meer bekijken',
    vipReceive: 'Ontvang een set van {tasks} productoptimalisatietaken.',
    vipEach: 'De winst per productoptimalisatie is {commission}.',
    vipCombined: 'De gecombineerde winst is {comboProfit}.',
    vipActivate: 'Activeer met {amount}.',
    vipDaily: 'Er kunnen dagelijks maximaal 3 sets worden voltooid.',
    home: 'Home',
    starting: 'Start',
    records: 'Records',
    loginTagline: 'Een responsieve optimalisatiewerkruimte voor web en mobiel.',
    signInContinue: 'Meld u aan om taken te blijven optimaliseren en volgen.',
    loginPrompt: 'Log in om door te gaan',
    username: 'Gebruikersnaam',
    password: 'Wachtwoord',
    enterUsername: 'Voer gebruikersnaam in',
    enterPassword: 'Voer wachtwoord in',
    login: 'Inloggen',
    signingIn: 'Bezig met inloggen...',
    faqP1: 'De kern van onze filosofie is een sterke toewijding aan u, onze gewaardeerde gebruikers. We begrijpen dat een dynamisch platform zoals het onze vragen kan oproepen die standaard FAQ’s niet altijd beantwoorden. Daarom staat ons klantenserviceteam altijd klaar om te helpen.',
    faqP2: 'We beantwoorden niet alleen vragen, maar bieden ook oplossingen zodat uw ervaring soepel en plezierig blijft. Als u een uitdaging ervaart, neem dan contact op met een van onze specialisten, beschikbaar van 10.00 tot 22.00 uur.',
    faqP3: 'Uw tevredenheid is niet alleen onze topprioriteit, maar ook onze passie. Laat ons u begeleiden, ondersteunen en elke stap van uw reis met u vieren.',
  },
  tr: {
    guest: 'Misafir',
    welcomeBack: '👋 Tekrar hoş geldin, {name}!',
    menu: 'Menü',
    list: 'Liste',
    service: 'Servis',
    event: 'Etkinlik',
    withdrawal: 'Çekim',
    deposit: 'Yatırma',
    terms: 'Şartlar',
    certificate: 'Sertifika',
    faqs: 'SSS',
    vipLevels: 'VIP Seviyeleri',
    viewMore: 'Daha fazla',
    vipReceive: '{tasks} ürün optimizasyon görevi içeren bir set alın.',
    vipEach: 'Her ürün optimizasyonundan elde edilen kâr {commission}.',
    vipCombined: 'Birleşik optimizasyon kârı {comboProfit}.',
    vipActivate: '{amount} ile etkinleştirin.',
    vipDaily: 'Günde en fazla 3 görev seti tamamlanabilir.',
    home: 'Ana Sayfa',
    starting: 'Başlat',
    records: 'Kayıtlar',
    loginTagline: 'Web ve mobil için duyarlı bir optimizasyon çalışma alanı.',
    signInContinue: 'Görevleri optimize etmeye ve kayıtları izlemeye devam etmek için giriş yapın.',
    loginPrompt: 'Devam etmek için giriş yapın',
    username: 'Kullanıcı adı',
    password: 'Şifre',
    enterUsername: 'Kullanıcı adını girin',
    enterPassword: 'Şifreyi girin',
    login: 'Giriş yap',
    signingIn: 'Giriş yapılıyor...',
    faqP1: 'Felsefemizin merkezinde size, değerli kullanıcılarımıza, güçlü bir bağlılık yer alır. Bizim gibi dinamik bir platformun standart SSS’lerin cevaplayamadığı sorular doğurabileceğini biliyoruz. Bu nedenle müşteri hizmetleri ekibimiz her zaman yardıma hazırdır.',
    faqP2: 'Sadece sorularınızı yanıtlamakla kalmıyor, aynı zamanda deneyiminizin sorunsuz ve keyifli olması için çözümler sunuyoruz. Bir sorun yaşarsanız, 10:00 ile 22:00 arasında hizmet veren uzmanlarımızla iletişime geçin.',
    faqP3: 'Memnuniyetiniz sadece önceliğimiz değil, aynı zamanda tutkumuzdur. Bu yolculuğun her adımında size rehberlik etmemize ve destek olmamıza izin verin.',
  },
  pt: {
    guest: 'Convidado',
    welcomeBack: '👋 Bem-vindo de volta, {name}!',
    menu: 'Menu',
    list: 'Lista',
    service: 'Serviço',
    event: 'Evento',
    withdrawal: 'Levantamento',
    deposit: 'Depósito',
    terms: 'T & C',
    certificate: 'Certificado',
    faqs: 'FAQs',
    vipLevels: 'Níveis VIP',
    viewMore: 'Ver mais',
    vipReceive: 'Receba um conjunto de {tasks} tarefas de otimização de produtos.',
    vipEach: 'O lucro por cada otimização de produto é {commission}.',
    vipCombined: 'O lucro combinado da otimização é {comboProfit}.',
    vipActivate: 'Ative com {amount}.',
    vipDaily: 'Até 3 conjuntos de tarefas podem ser concluídos por dia.',
    home: 'Início',
    starting: 'Começar',
    records: 'Registos',
    loginTagline: 'Um espaço de otimização responsivo para web e mobile.',
    signInContinue: 'Entre para continuar a otimizar tarefas e acompanhar registos.',
    loginPrompt: 'Inicie sessão para continuar',
    username: 'Nome de utilizador',
    password: 'Palavra-passe',
    enterUsername: 'Introduza o nome de utilizador',
    enterPassword: 'Introduza a palavra-passe',
    login: 'Entrar',
    signingIn: 'A entrar...',
    faqP1: 'No centro da nossa filosofia está um forte compromisso consigo, nosso estimado utilizador. Sabemos que uma plataforma dinâmica como a nossa pode gerar perguntas que as FAQs padrão nem sempre resolvem. Por isso, a nossa equipa de apoio ao cliente está sempre pronta para ajudar.',
    faqP2: 'Não respondemos apenas às suas perguntas, também oferecemos soluções para garantir que a sua experiência seja simples, agradável e satisfatória. Se tiver algum desafio, contacte um dos nossos especialistas disponíveis das 10h às 22h.',
    faqP3: 'A sua satisfação não é apenas a nossa prioridade, é a nossa paixão. Permita-nos orientá-lo, apoiá-lo e celebrar cada passo desta jornada consigo.',
  },
};

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  languages: typeof languageOptions;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    if (saved && languageOptions.some((item) => item.code === saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    localStorage.setItem(STORAGE_KEY, nextLanguage);
  };

  const t = (key: string, vars?: Record<string, string | number>) => {
    let value = translations[language][key] ?? translations.en[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([name, replacement]) => {
        value = value.replace(new RegExp(`\\{${name}\\}`, 'g'), String(replacement));
      });
    }
    return value;
  };

  const value = useMemo(
    () => ({ language, setLanguage, languages: languageOptions, t }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
